select * from syscat.tables where tabname like '%as%' fetch first 10 rows only;commit;
select * from syscat.views where viewname like '%%' and viewschema like '%%' fetch first 10 rows only;commit;
select * from syscat.functions where funcname like '%%' and funcschema like '%%' fetch first 10 rows only;commit;

SELECT HSN, PIN, DBPARTITIONNUM(PIN) AS PARTITION_NUM
			FROM THIS.TABLEORVIEW
			WHERE COLUM='SOMETHING'
			WITH UR;commit;

LIST DB DIRECTORY; commit;
LIST NODE DIRECTORY; commit;
GET DB CONFIG FOR dbalias; COMMIT;

-- Get partitions
SELECT TABSCHEMA, TABNAME 
FROM SYSCAT.COLUMNS
WHERE COLNAME = 'PARTITION_NUM'
with ur; commit;

SELECT INDNAME, DEFINER, TABSCHEMA, TABNAME, 
COLNAMES, COLCOUNT, UNIQUERULE, INDEXTYPE 
FROM SYSCAT.INDEXES
WHERE TABSCHEMA NOT LIKE 'SYS%' AND
TABNAME = 'TABLE_NAME'

SELECT SUBSTR(tabname, 1,16) tabname, 
SUBSTR(datapartitionname, 1, 12) datapartitionname, 
seqno, SUBSTR(lowvalue, 1, 12) as lowvalue, LOWINCLUSIVE, 
SUBSTR(highvalue, 1, 12) as highvalue,HIGHINCLUSIVE 
FROM SYSCAT.DATAPARTITIONS WHERE TABNAME='SALDOCONTABIL' ORDER BY seqno with ur;commit;

SELECT * FROM SYSCAT.BUFFERPOOLDBPARTITIONS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSCAT.DBPARTITIONGROUPDEF FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSCAT.EVENTMONITORS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSCAT.PACKAGES FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBM.SYSPLAN FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBM.SYSTASKS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.ADMINTABCOMPRESSINFO FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.ADMINTABINFO FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.APPLICATIONS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.APPL_PERFORMANCE FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.BP_HITRATIO FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.BP_READ_IO FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.BP_WRITE_IO FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.CONTAINER_UTILIZATION FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.DBCFG FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.DBPATHS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.DB_HISTORY FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.ENV_SYS_RESOURCES FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.LOCKS_HELD FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.LOCKWAITS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.LOG_UTILIZATION FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.LONG_RUNNING_SQL FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.PDLOGMSGS_LAST24HOURS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.QUERY_PREP_COST FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.REG_VARIABLES FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPAGENT FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPAGENT_MEMORY_POOL FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPAPPL FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPAPPL_INFO FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPBP FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPBP_PART FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPCONTAINER FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPDB FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPDBM FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPDBM_MEMORY_POOL FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPDB_MEMORY_POOL FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPDETAILLOG FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPDYN_SQL FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPFCM FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPFCM_PART FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPHADR FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPLOCK FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPLOCKWAIT FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPSTMT FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPSTORAGE_PATHS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPSUBSECTION FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPSWITCHES FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPTAB FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPTAB_REORG FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPTBSP FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPTBSP_PART FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPTBSP_QUIESCER FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPTBSP_RANGE FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPUTIL FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.SNAPUTIL_PROGRESS FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.TBSP_UTILIZATION FETCH FIRST 1 ROWS ONLY;COMMIT;
SELECT * FROM SYSIBMADM.TOP_DYNAMIC_SQL FETCH FIRST 1 ROWS ONLY;COMMIT;

